#!/bin/bash

# Setup script for software development on Linux
# System specs: Ubuntu 19.04

# SOURCES
# -------

sudo apt install -y build-essential libssl-dev vim vim-gnome git curl imagemagick chromium-browser virtualbox zsh xclip openvpn network-manager-openvpn-gnome ffmpeg

# chrome
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

# spotify
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886 0DF731E45CE24F27EEEB1450EFDC8610341D9410
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list

# yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt update
sudo apt install -y google-chrome-stable spotify-client yarn

# DOWNLOADS
# ---------

# node
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
# close and reopen your terminal to start using nvm or run the following to use it now:
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm install node
nvm install 8
nvm alias default 8

# oh-my-zsh
sudo apt install -y zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
chsh -s $(which zsh)

# a vim distribution with kewl extensions
curl -L https://bit.ly/janus-bootstrap | bash
echo 'color molokai' >> ~/.gvimrc.after

# PROFILE
# -------

# update .zshrc with NVM vars
cat ~/.bashrc | tail -n 3 >> ~/.zshrc

git config --global core.editor vim
